blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/cleevio/cleeviox-toolkit#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/cleevio/cleeviox-toolkit/discussions
    about: Ask questions and discuss ideas
