name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: bun run test:cov
      # TODO -- Add codecov.io to organization
      # https://app.codecov.io/github/cleeviox 
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: packages/knip/coverage/lcov.info
